### ISSUE TITLE
Capability to specify the names of "cassandra_migration_version*" tables

### ISSUE THREAD

**Issue by james-hu** [hhandoko/cassandra-migration#16]
## Outcome Desired

Be able to specify the names of "cassandra_migration_version*" tables in `KeyspaceConfiguration` or `CassandraMigration`
- Table name prefix or suffix or full name can be specified
- This allows multiple independent applications or modules share the same keyspace while all using cassandra-migration without interfering with each other

<hr>
## Definition of Done

Table name prefix or suffix or full name can be specified in `KeyspaceConfiguration` or `CassandraMigration`, therefore,
- Multiple migrations can be tracked in the same keyspace.

<hr>
## Out of Scope

<hr>
## How to Demo
1. Do migration with some .cql files on a keyspace
2. Do another independent migration with some other .cql files and different names of "cassandra_migration_version*" tables on the same keyspace
3. Check to confirm both migrations succeeded.

**Comment by james-hu** [comment]
Just wrote my first lines of Kotlin code, and created a pull request :-)

**Comment by hhandoko** [comment]
Thanks @james-hu 👍 I've reviewed and merged the PR.
