### ISSUE TITLE
Make consistency level configurable

### ISSUE THREAD

**Issue by james-hu** [hhandoko/cassandra-migration#20]
## Make it configurable: consistency level for schema version tracking statements

Currently it is hard coded to ALL, making it configurable gives us possibilities to work around some issues (in very sick use cases, I have to admit).

I have a quick implementation here: https://github.com/james-hu/cassandra-migration/pull/1/files
But probably the configuration should be on CassandraMigration rather than on KeyspaceConfiguration. Then we can pass it as an argument to the constructor of SchemaVersionDAO. That change seems to be a little bit structural. So I think I'd better let you take over.

<hr>
## Definition of Done

Consistency level is configurable from Java (and command line as well?)

<hr>
## Out of Scope

Consistency level of migrations scripts provided by the users.

<hr>
## How to Demo

Create a keyspace that can't satisfy the ConsistencyLevel.ALL, and try to make migration success by setting consistency level to QUORUM.

**Comment by smiklosovic** [comment]
@hhandoko  we need this badly, please release this as soon as possible

**Comment by hhandoko** [comment]
Thanks for reaching out @smiklosovic , I'm just a bit inundated at work right now. If you could draft a PR it would really help me 😄 Otherwise, I'll try to get to this on my next opportunity.

**Comment by hhandoko** [comment]
Partly implemented in #46 . I might expand this to accept user-defined values over configuration files.

**Comment by hhandoko** [comment]
Implemented in #48.
