### ISSUE TITLE
Import dependency using SBT

### ISSUE THREAD

**Issue by OuesFa** [hhandoko/cassandra-migration#36]
Is it possible to import the dependency using SBT ?

## Expected Behaviour

I'm using sbt.version=0.13.9
Trying to import dependency:
  "com.builtamont" % "cassandra-migration" % "0.9"

<hr>

## Actual Behaviour

*<Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving org.scalamock#scalamock-scalatest-support_2.10;3.2.2 ...
[info] Resolving org.scalamock#scalamock-core_2.10;3.2.2 ...
[info] Resolving org.scala-lang#scala-library;2.10.5 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.builtamont#cassandra-migration;0.9: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.builtamont:cassandra-migration:0.9 (/home/ubuntu/dtl-spark/build.sbt#L8-26)
[warn] 		  +- default:dtl-spark_2.10:0.0.3
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.builtamont#cassandra-migration;0.9: not found
[error] (*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: com.builtamont#cassandra-migration;0.9: not found
[error] Total time: 57 s, completed 29 déc. 2016 11:16:02</pre>></a>>*

**Comment by hhandoko** [comment]
Hi @OuesFa , can you provide a snippet of your `build.sbt`?

Otherwise, the only suggestion I can offer is to try clearing your `com.builtamont` ivy / sbt dependency cache folders (if it exists).

PS. I'm using this library from a couple of Play (Scala) projects with SBT.

**Comment by hhandoko** [comment]
Hi @OuesFa , any update on your issue? Have you tried clearing the cache?

**Comment by OuesFa** [comment]
Hello, thanks for your reply.
Here is my my build.sbt file :

```
name := "spark-app"
 
version := "0.0.3"
 
scalaVersion := "2.10.6"
 
libraryDependencies ++= Seq(
  "org.scalaj" %% "scalaj-http" % "2.3.0",
  "org.scalatest" %% "scalatest" % "2.2.6" % "test",
  "com.sun.mail" % "javax.mail" % "1.5.5",
  "org.scalamock" %% "scalamock-scalatest-support" % "3.2.2" % "test",
  "org.apache.spark" %% "spark-core" % "1.6.1" % "provided",
  "org.apache.spark" %% "spark-sql" % "1.6.1",
  "org.apache.spark" %% "spark-hive" % "1.6.1",
  "org.apache.spark" %% "spark-mllib" % "1.6.1",
  "org.apache.spark" %% "spark-streaming" % "1.6.1",
  "org.apache.spark" %% "spark-streaming-kafka" % "1.6.1",
  "com.datastax.spark" %% "spark-cassandra-connector" % "1.6.0-M2",
  "com.datastax.cassandra" % "cassandra-driver-core" % "3.0.2",
  "com.datastax.cassandra" % "cassandra-driver-extras" % "3.0.2",
  "org.elasticsearch" %% "elasticsearch-spark" % "2.2.0",
  "com.sksamuel.elastic4s" %% "elastic4s-streams" % "1.7.4"
)
 
test in assembly := {}
 
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) =>
    (xs map {_.toLowerCase}) match {
      case ("manifest.mf" :: Nil) | ("index.list" :: Nil) | ("dependencies" :: Nil) => MergeStrategy.discard
      case _ => MergeStrategy.discard
    }
  case "application.conf"                            => MergeStrategy.concat
  case _                                => MergeStrategy.first
}
 
fork in run := true
 
parallelExecution in Test := false
```

Sorry for the late response, I'm on a trip :)
So I can't clear the cache for now.

**Comment by hhandoko** [comment]
Hi @OuesFa , I can't see any reference for `cassandra-migration` on your `build.sbt`, was this the working one (i.e. with the failed fetch dependency removed)?

**Comment by OuesFa** [comment]
yup exactly
I've just added the cassandra migration line 
"com.builtamont" % "cassandra-migration" % "0.9"

**Comment by hhandoko** [comment]
Hi @OuesFa , sorry for the late reply.

I was not able to replicate your problem using the provided `build.sbt` file, i.e. everything downloaded correctly for me.

Can you please check your global SBT repositories config at `~/.sbt/repositories` and see if `maven-central` entry appears on it?

For reference, here is mine:

```
[repositories]
  local
  maven-central
  typesafe-releases: http://repo.typesafe.com/typesafe/releases
  typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

**Comment by hhandoko** [comment]
Hi @OuesFa , have you had the chance to try my suggestion? Or have you managed to fix it?

**Comment by hhandoko** [comment]
I'm closing this issue as there's no further feedback.
