### ISSUE TITLE
Compatibility with cassandra-driver-core 3.3.0 ?

### ISSUE THREAD

**Issue by goerge** [hhandoko/cassandra-migration#65]
Is `cassandra-migration` `0.11` compatible with `datastax cassandra-driver-core` `3.3.0`?

`cassandra-migration` depends on `datastax cassandra-driver-core` `3.0.6` which has a compatibility issue with `Guava` `20` (see https://datastax-oss.atlassian.net/browse/JAVA-1328)

Is it safe to force a newer version of `datastax cassandra-driver-core` (at least `3.2.0`) when using `cassandra-migration` `0.11`?

**Comment by hhandoko** [comment]
Hi @goerge , I have not tested it yet against newer `cassandra-driver-core` versions.

My plan was to bring the drivers up-to-date post `v1` (pending the implementation of callbacks). I can put this as a priority, and if nothing major breaks:

- `0.12` - Update drivers to `3.1.x`
- `0.13` - Update drivers to `3.2.x`
- `0.14` - Update drivers to `3.3.x`

PS. I've updated the roadmap to suit: [https://github.com/builtamont-oss/cassandra-migration/wiki/Roadmap](https://github.com/builtamont-oss/cassandra-migration/wiki/Roadmap)

**Comment by spolamraju** [comment]
cqlsh connects fine. however,
 java  -jar -Dcassandra.migration.scripts.locations=filesystem:sql/CaaS  -Dcassandra.migration.scripts.locations=filesystem:sql/CaaS -Dcassandra.migration.table.prefix=another_app_ -Dcassandra.migration.cluster.contactpoints=xxx..xx.xxx.xxx -Dcassandra.migration.cluster.port=9042 -Dcassandra.migration.cluster.username=xyz   -Dcassandra.migration.cluster.password=abc -Dcassandra.migration.keyspace.name=xxx -Dcassandra.migration.keyspace.consistency=QUORUM jars/cassandra-migration-0.11-jar-with-dependencies.jar  migrate  throws following error

Cassandra Migration 0.11
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /xxx.xx.xxx.xxxx:9042 (com.datastax.driver.core.exceptions.TransportException: [xxx.xx.xxxx.xxx:9042] Channel has been closed))
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)

cqlsh version [cqlsh 5.0.1 | Cassandra 2.1.14 | DSE  | CQL spec 3.2.1 | Native protocol v3]

**Comment by Ignas** [comment]
I think this happens when calculateVersionRank tries to execute an empty batch.

**Comment by hhandoko** [comment]
v`0.15` which uses `cassandra-driver` 3.3.x has been published, it should be synced to Maven Central within 48 hours.
