### ISSUE TITLE
Is there any way to stop the next migrations when one migration fails ?

### ISSUE THREAD

**Issue by elzinko** [hhandoko/cassandra-migration#68]
Hi there!
All is in the title. 
I use this tool to launch some spark migration. I can knownb if my Spark job succed or not. In the case it is in error, I cannot find a way to stop the next migrations : 
JavaMigration implements "public void migrate(Session session) throws Exception" 
Is there any way I am not aware to stop the migrations in case of an error?
Thanks

**Comment by elzinko** [comment]
# My fault, I did not try to throw an Exception ...

**Comment by hhandoko** [comment]
No worries, glad you found a solution!
