### ISSUE TITLE
about the maven-badges-generator

### ISSUE THREAD

**Issue by Ivan97** [hhandoko/cassandra-migration#74]
try this :)
```
[![Maven Central](https://maven-badges-generator.herokuapp.com/image/com.hhandoko/cassandra-migration)](https://maven-badges-generator.herokuapp.com/dependency/com.hhandoko/cassandra-migration)
```
[![Maven Central](https://maven-badges-generator.herokuapp.com/image/com.hhandoko/cassandra-migration)](https://maven-badges-generator.herokuapp.com/dependency/com.hhandoko/cassandra-migration)

**Comment by hhandoko** [comment]
Thank you 👍
